# Generated by Django 6.0.2 on 2026-02-20 03:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nutrient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.BigIntegerField(db_index=True, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('unit_name', models.CharField(blank=True, default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fdc_id', models.BigIntegerField(db_index=True, unique=True)),
                ('name', models.CharField(max_length=512)),
                ('data_type', models.CharField(default='foundation', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ProductNutrient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(blank=True, null=True)),
                ('nutrient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nutrition.nutrient')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nutrition.product')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('product', 'nutrient'), name='uniq_product_nutrient')],
            },
        ),
    ]
