# Generated by Django 6.0.2 on 2026-02-24 00:08

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nutrient',
            name='external_id',
        ),
        migrations.RemoveField(
            model_name='nutrient',
            name='unit_name',
        ),
        migrations.RemoveField(
            model_name='product',
            name='data_type',
        ),
        migrations.RemoveField(
            model_name='product',
            name='fdc_id',
        ),
        migrations.RemoveField(
            model_name='productnutrient',
            name='amount',
        ),
        migrations.AddField(
            model_name='nutrient',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nutrient',
            name='display_order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='nutrient',
            name='is_macro',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='nutrient',
            name='unit',
            field=models.CharField(default='g', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nutrient',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='nutrient',
            name='usda_nutrient_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='data_source',
            field=models.CharField(default='USDA', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='product',
            name='usda_fdc_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='productnutrient',
            name='amount_per_100g',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productnutrient',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productnutrient',
            name='data_source',
            field=models.CharField(default='USDA', max_length=50),
        ),
        migrations.AddField(
            model_name='productnutrient',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='nutrient',
            name='name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='productnutrient',
            name='nutrient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_nutrients', to='nutrition.nutrient'),
        ),
        migrations.AlterField(
            model_name='productnutrient',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_nutrients', to='nutrition.product'),
        ),
        migrations.AddConstraint(
            model_name='nutrient',
            constraint=models.UniqueConstraint(fields=('name', 'unit'), name='uniq_nutrient_name_unit'),
        ),
        migrations.AddConstraint(
            model_name='productnutrient',
            constraint=models.CheckConstraint(condition=models.Q(('amount_per_100g__gte', 0)), name='chk_amount_per_100g_non_negative'),
        ),
    ]
