# Generated by Django 6.0.2 on 2026-03-09 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0003_product_properties_product_tags_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('age', models.PositiveIntegerField()),
                ('sex', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('na', 'N/A')], default='na', max_length=10)),
                ('height_cm', models.DecimalField(decimal_places=2, max_digits=6)),
                ('weight_kg', models.DecimalField(decimal_places=2, max_digits=6)),
                ('body_fat_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('activity', models.CharField(choices=[('static', 'Static'), ('mild', 'Mild'), ('moderate', 'Moderate'), ('high', 'High'), ('exhausting', 'Exhausting')], default='moderate', max_length=20)),
                ('goal', models.CharField(choices=[('maintenance', 'Maintenance'), ('cut', 'Cut'), ('bulk', 'Bulk')], default='maintenance', max_length=20)),
            ],
            options={
                'indexes': [models.Index(fields=['sex', 'age'], name='nutrition_u_sex_f9daa5_idx')],
            },
        ),
        migrations.CreateModel(
            name='NutrientNorm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sex', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('na', 'N/A')], default='na', max_length=10)),
                ('age_min', models.PositiveIntegerField()),
                ('age_max', models.PositiveIntegerField()),
                ('recommended_amount', models.DecimalField(decimal_places=4, max_digits=10)),
                ('upper_limit', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('source', models.CharField(blank=True, default='', max_length=255)),
                ('note', models.TextField(blank=True, default='')),
                ('nutrient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='norms', to='nutrition.nutrient')),
            ],
            options={
                'indexes': [models.Index(fields=['sex', 'age_min', 'age_max'], name='nutrition_n_sex_ed19c2_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('age_min__gte', 0)), name='norm_age_min_non_negative'), models.CheckConstraint(condition=models.Q(('age_max__gte', 0)), name='norm_age_max_non_negative'), models.CheckConstraint(condition=models.Q(('recommended_amount__gte', 0)), name='norm_recommended_amount_non_negative')],
            },
        ),
    ]
