# Generated by Django 6.0.2 on 2026-03-10 18:41

import django.contrib.postgres.fields
import django.contrib.postgres.indexes
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0004_userprofile_nutrientnorm'),
    ]

    operations = [
        migrations.CreateModel(
            name='MealLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meal_type', models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('snack', 'Snack')], default='lunch', max_length=20)),
                ('logged_at', models.DateTimeField()),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_logs', to='nutrition.userprofile')),
            ],
            options={
                'ordering': ['-logged_at'],
            },
        ),
        migrations.CreateModel(
            name='MealLogItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('grams', models.DecimalField(decimal_places=2, max_digits=8)),
                ('meal_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='nutrition.meallog')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_log_items', to='nutrition.product')),
            ],
        ),
        migrations.CreateModel(
            name='UserPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('diet_type', models.CharField(choices=[('omnivore', 'Omnivore'), ('vegetarian', 'Vegetarian'), ('vegan', 'Vegan'), ('keto', 'Keto'), ('high_protein', 'High protein')], default='omnivore', max_length=20)),
                ('preferred_tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list)),
                ('excluded_tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list)),
                ('preferred_properties', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list)),
                ('excluded_properties', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list)),
                ('notes', models.TextField(blank=True, default='')),
                ('user_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to='nutrition.userprofile')),
            ],
        ),
        migrations.AddIndex(
            model_name='meallog',
            index=models.Index(fields=['user_profile', 'logged_at'], name='nutrition_m_user_pr_f5eac5_idx'),
        ),
        migrations.AddIndex(
            model_name='meallog',
            index=models.Index(fields=['meal_type'], name='nutrition_m_meal_ty_94c678_idx'),
        ),
        migrations.AddIndex(
            model_name='meallogitem',
            index=models.Index(fields=['meal_log'], name='nutrition_m_meal_lo_2eab24_idx'),
        ),
        migrations.AddIndex(
            model_name='meallogitem',
            index=models.Index(fields=['product'], name='nutrition_m_product_b8ba41_idx'),
        ),
        migrations.AddConstraint(
            model_name='meallogitem',
            constraint=models.CheckConstraint(condition=models.Q(('grams__gt', 0)), name='meal_log_item_grams_positive'),
        ),
        migrations.AddIndex(
            model_name='userpreferences',
            index=django.contrib.postgres.indexes.GinIndex(fields=['preferred_tags'], name='pref_tags_gin'),
        ),
        migrations.AddIndex(
            model_name='userpreferences',
            index=django.contrib.postgres.indexes.GinIndex(fields=['excluded_tags'], name='excl_tags_gin'),
        ),
        migrations.AddIndex(
            model_name='userpreferences',
            index=django.contrib.postgres.indexes.GinIndex(fields=['preferred_properties'], name='pref_props_gin'),
        ),
        migrations.AddIndex(
            model_name='userpreferences',
            index=django.contrib.postgres.indexes.GinIndex(fields=['excluded_properties'], name='excl_props_gin'),
        ),
    ]
