# Generated by Django 6.0.2 on 2026-04-24 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0009_userprofile_password_reset_requested_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nutrient',
            options={'ordering': ['display_order', 'name']},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name']},
        ),
        migrations.AddConstraint(
            model_name='nutrientnorm',
            constraint=models.CheckConstraint(condition=models.Q(('age_max__gte', models.F('age_min'))), name='norm_age_max_gte_age_min'),
        ),
    ]
